# Generated by Django 4.1.3 on 2023-11-04 14:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0002_categories_alter_course_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="slug",
            field=models.SlugField(default=""),
        ),
        migrations.AlterField(
            model_name="categories",
            name="id",
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name="course",
            name="date",
            field=models.DateField(
                verbose_name=datetime.datetime(2023, 11, 4, 17, 49, 20, 628222)
            ),
        ),
    ]
