# Generated by Django 4.1.3 on 2023-11-06 07:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0004_course_isuptaded_alter_course_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categories",
            name="id",
            field=models.BigAutoField(
                auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
            ),
        ),
        migrations.AlterField(
            model_name="categories",
            name="slug",
            field=models.SlugField(blank=True, default="", editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="course",
            name="date",
            field=models.DateField(
                verbose_name=datetime.datetime(2023, 11, 6, 10, 20, 18, 791090)
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="slug",
            field=models.SlugField(blank=True, default="", editable=False, unique=True),
        ),
    ]
