# Generated by Django 4.1.3 on 2023-11-06 09:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0005_alter_categories_id_alter_categories_slug_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="courses.categories",
            ),
        ),
        migrations.AlterField(
            model_name="course",
            name="date",
            field=models.DateField(
                verbose_name=datetime.datetime(2023, 11, 6, 12, 6, 14, 850303)
            ),
        ),
    ]
