# Generated by Django 4.2.7 on 2023-11-08 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0008_alter_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='Categories',
            field=models.ManyToManyField(to='courses.categories'),
        ),
    ]
