# Generated by Django 4.2.7 on 2023-11-08 07:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_course_categories'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='Categories',
            new_name='categories',
        ),
    ]
