# Generated by Django 4.2.7 on 2023-11-08 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_rename_categories_course_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='course',
            name='category',
        ),
    ]
