# Generated by Django 4.2.7 on 2023-11-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_remove_course_categories_remove_course_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(to='courses.categories'),
        ),
    ]
