# Generated by Django 4.2.7 on 2023-11-08 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0012_course_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='categories',
        ),
    ]
